name: teslo_shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: 2.4.4
  flutter_riverpod: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^1.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3

flutter_native_splash:
  # image: assets/imgs/logo_completoMenu.jpg
  image: assets/loaders/bottle-loader.gif
  # branding: assets/imgs/logo-completoMenu.jpg
  # color_dark: "#121212
  # image_dark: assets/imgs/logo-completoMenu.jpg
  # branding_dark: assets/imgs/logo-completoMenu.jpg
  android_12:
    # image: assets/imgs/logo_completoMenu.jpg
    image: assets/icon/icon.jpg
    image_dark: assets/icon/icon.jpg

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
    - assets/icon/
